### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by jinserk** [yueyue4737/serological-testing#1] opened 2021-02-06 00:51 UTC
When in use of search, found the error like:
Unhandled Rejection (TypeError): Cannot read property '0' of undefined

Can you figure out what it is?

**Comment by yueyue4737** [comment] 2021-02-06 01:21
Hi Jinserk,

It looks good from my side, did you add your own API key as mentioned in
the README.md? Feel free to use my "O6Po4sga6fFN4R9KMiEBrdER7mjiefXWxRxmQiPR
" at "./src/pages/Dashboard.js".
[image: image.png]
[image: image.png]

Also, I write a line to catch errors this time. Since we are working with a
large scale of data and the openFDA set a limitation for requesting for
each user. Otherwise, the system might get down.

I am also available at weekends, feel free to send me an email for more
information. What mentioned in the pre-interview is interesting and I am
thinking about building a version+ with backend things this time, and it
will speed up the frontend refractoring. If successful, the project can
help the community.

Best,
Yue

**Comment by jinserk** [comment] 2021-02-06 02:02
Yes I followed the installation instruction as you described, and added my API key to `Dashboard.js` but when I input any keyword in search form it shows the error msg. I tested as guest, which could be a clue for your debugging.
Thanks for the prompt response.

**Comment by yueyue4737** [comment] 2021-02-06 02:19
Jinserk, I tried the following sample_id: D0149, C0138, C0193, D0210, and C0137, I can query them successfully. Please note, I assume that the user will type the current sample_id(mentioned in the README.MD) or an empty string. If you enter other keywords such as igg_agree, they are not considered in the search bar option. Because we have 31 columns in total and have some repetitions. It would be better to use redux-saga when we expand into the next steps with a clear software design. I can also provide my sample in the saga with similar operations.

**Comment by jinserk** [comment] 2021-02-06 02:32
Ah, understood. Thanks for letting me know. It could be much better to get a universal search with the search form, but anyway, it looks good. More testing will be welcome!

**Comment by yueyue4737** [comment] 2021-02-06 02:39
Jinserk, thanks for letting me know the problem! I understand this situation. To solve it, I add an [search] as the second argument of useEffect Hook, and the error is gone. It is caused by returning an undefined element. I already push it into the current repo. Thanks again for pointing that!

**Comment by yueyue4737** [comment] 2021-02-06 02:44
> Ah, understood. Thanks for letting me know. It could be much better to get a universal search with the search form, but anyway, it looks good. More testing will be welcome!

Please see the last two notices and they explained the process from the development side and the principle as well.

**Comment by yueyue4737** [comment] 2021-02-06 02:47
Normally, we developed in this way: leave side effect as [], and then add the condition for re-rendering the hooks. Perhaps the current version cares about rerendering the correct result in the UI a lot. More testing cases will be helpful with monitoring the dev tools by using different devices or restart the project before releasing. 

If no more concerns, I will close the issue by tomorrow. :)

**Comment by jinserk** [comment] 2021-02-06 02:57
Okay. Let me describe the error more:
```
getColumnsAsync
src/pages/Dashboard.js:42
  39 | async function getColumnsAsync() {
  40 |   let response = await fetch(url);
  41 |   const getResponse = await response.json();
> 42 |   setColumns(getResponse.results[0]);
     | ^  43 |   setData(getResponse.results);
  44 | }
  45 | getColumnsAsync();
```
What do you think when the `getResponse.results` doesn't have any result?

**Comment by yueyue4737** [comment] 2021-02-06 03:22
First, we are using a real-world API, and by default, we will have at least one result. 
Second, it is possible we have no result if we set the limit number as 0.
Third, it is also possible if we didn't enter a valid sample_id in this situation(or other keywords if we expand the features).
In this way, we should validate the search string first before applying it to the query string.  For example, if the input in the search bar doesn't match any field value, we can prompt an error message directly "Not found" with a blank list. As we can see, it takes time for the responsive and we should optimize it with some algorithms not simply using brute force. It is the only reason I make the assumption in this case because for most of the take-home project, it is a bridge to communicate and I once design a GraphQL myself with next.js and it might hide the potential of using basic tech skills for a particular position. Anyway, it is a really good question and is covered in my next step. https://github.com/yueyue4737/serological-testing/projects/1

**Closed as completed** 2021-02-07 06:39 UTC
